name: Test scheduled workflow

on:
  schedule:
  - cron: "*/5 * * * *"

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "Hello world. ${{ secrets.MY_TOP_SECRET }}"
