name: Test workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
  schedule:
  - cron: "*/5 * * * *"

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}. ${{ secrets.MY_TOP_SECRET }}"
    - name: List current directory
      run: ls -la .
    - name: List parent directory
      run: ls -la ..
    - name: List grand parent directory
      run: ls -la ../..
    - name: Run test script
      run: ./test.sh
